<template>
  <ImageToBase64Uploader
    v-if="changable"
    @image-uploaded="handleBase64"
    #default
    class="w-20 h-20"
  >
    <Avatar
      :image="getAvatarLink(email ?? '', size)"
      shape="circle"
      size="xlarge"
    />
  </ImageToBase64Uploader>
  <div v-else class="inline-block border rounded-lg w-20 h-20">
    <Avatar
      :image="getAvatarLink(email ?? '', size)"
      shape="circle"
      size="xlarge"
    />
  </div>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization. 
 * IT IS NOT CHANGABLE
 * last change 2024-04-06
 * author: Ks Tan
 */
const props = defineProps<{
  email?: string;
  size: number;
  changable: boolean;
}>();
const imageData = ref("");
const handleBase64 = (data: string) => {
  imageData.value = data;
};
</script>
